# SPDX-FileCopyrightText: 2022 Kevin Amado <kamadorueda@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[dependencies]

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
description = "A lexing and parsing toolkit for Rust"
edition = "2021"
license = "GPL-3.0-only"
name = "santiago"
repository = "https://github.com/kamadorueda/santiago"
version = "0.1.0"
