[dependencies]

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
description = "A lexing and parsing toolkit for Rust"
edition = "2021"
name = "santiago"
repository = "https://github.com/kamadorueda/santiago"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
